--- 
abstract: Sledge's session manger switcher
author: 
  - TOKUHIRO Matsuno <tokuhirom at mobilefactory dot jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sledge-SessionManager-Auto
no_index: 
  directory: 
    - inc
    - t
version: 0.03
